In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text' : ['people watch campus','campus watch campus','people write comment','campus write comment'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch campus       1
1   campus watch campus       1
2  people write comment       0
3  campus write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
# it gives output in alphabetic order
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [8]:
# checking vocab with random sentence
cv.transform(["watch dog campus comment"]).toarray()

array([[1, 1, 0, 1, 0]])

N-Gram

In [9]:
cv = CountVectorizer(ngram_range=(2,2))

In [10]:
bow = cv.fit_transform(df['text'])

In [11]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campus': 4, 'campus watch': 0, 'people write': 3, 'write comment': 5, 'campus write': 1}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


In [13]:
cv = CountVectorizer(ngram_range=(3,3))

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]
[[0 1 0 0]]


In [16]:
print(cv.vocabulary_)

{'people watch campus': 2, 'campus watch campus': 0, 'people write comment': 3, 'campus write comment': 1}
